services:
  - type: web
    name: portfolio
    env: node
    region: oregon # Choose the region closest to you or your audience
    plan: free # Upgrade as needed
    buildCommand: npm install && npm install --save-dev @vitejs/plugin-react && npx vite build && npx esbuild server/index.ts --platform=node --packages=external --bundle --format=esm --outdir=dist
    startCommand: node dist/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000 # Render assigns a PORT env variable, default 10000
    healthCheckPath: /